version: 2.1

jobs:
 build:
    docker:
      - image: cimg/base:2022.04
    steps:
      - checkout
      - run:
          command: wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb
          name: Pre-Install tasks
      - run:
          command: sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0
          name: Install dotnet-skd-6.0
      - run:
          name: "Install chrome"
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb
      - run:
          name: "Run Application Tests"
          command: dotnet test
workflows:
  test:
    jobs:
      - build