version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3
  node: circleci/node@4.7
  
jobs:
 build:
    docker:
      - image: cimg/node:16.13-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb
          name: Pre-Install tasks
      - run:
          command: sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0
          name: Install dotnet-skd-6.0
      - run:
          name: "Run Application Tests"
          command: dotnet test
workflows:
  test:
    jobs:
      - build